DROP DATABASE IF EXISTS newpaymybuddy;

CREATE DATABASE newpaymybuddy;

USE newpaymybuddy;




CREATE TABLE Identification (
IDN_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

IDN_EMAIL VARCHAR (100) NOT NULL,

IDN_PASSWORD VARCHAR (100) NOT NULL
);

INSERT INTO Identification  (IDN_EMAIL, IDN_PASSWORD) values('emmanueljurquet@gmail.com', 'nouveaumotdepasse');
INSERT INTO Identification (IDN_EMAIL, IDN_PASSWORD) values ('audrey@gmail.com','motdepasse2');
INSERT INTO Identification (IDN_EMAIL, IDN_PASSWORD) values ('jeannechureau@gmail.com','nouveaumdp3');




CREATE TABLE User (

USR_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

USR_FK_IDN INTEGER NOT NULL,

USR_F_NAME VARCHAR (100) NOT NULL,

USR_L_NAME VARCHAR (100) NOT NULL,

USR_EMAIL VARCHAR (100) NOT NULL,

USR_BIRTH DATE NOT NULL,

USR_ADDR VARCHAR (100) NOT NULL,

USR_PHONE VARCHAR (100) NOT NULL,

USR_CITY VARCHAR (100) NOT NULL,

USR_ZIP VARCHAR (100) NOT NULL,
 
FOREIGN KEY (USR_FK_IDN) REFERENCES Identification (IDN_ID));

INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('1','Emmanuel',' Jurquet','emmanueljurquet@gmail.com','1979/12/02','10 rue of nowhere',' 07-58-65-98','Paris', '75000');
INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('2','Audrey', 'Guillet','audrey@gmail.com','1984/05/12','10 rue of nowhere', '07-58-55-84','Paris', '75000');
INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('3','Jeanne','Chureau','jeannechureau@gmail.com','2013/02/07','10 rue de nulle part', '07-65-85-95', 'Paris','75000');




CREATE TABLE Wallet (

WAL_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
 
WAL_USR_FK_ID INTEGER NOT NULL,

WAL_BALANCE DECIMAL (10,3) NOT NULL,

WAL_VISA VARCHAR (100)  NOT NULL,

WAL_EXPIR VARCHAR (10) NOT NULL, 

WAL_CRYPTO INTEGER (5) NOT NULL,

FOREIGN KEY (WAL_USR_FK_ID) REFERENCES User ( USR_ID));

INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('1', '100.00', '231546598', '10/26', '415');
INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('2', '250.00','213556897', '01/24', '416');
INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('3', '10.00', '21356645', '05/25', '413');




CREATE TABLE Friend (

FR_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

FR_USR_PROFILE_ID_OWNER INTEGER NOT NULL,

FR_USR_PROFILE_ID_RECEIVER INTEGER NOT NULL,

FOREIGN KEY (FR_USR_PROFILE_ID_OWNER) REFERENCES User (USR_ID),

FOREIGN KEY (FR_USR_PROFILE_ID_RECEIVER) REFERENCES User (USR_ID)); 

INSERT INTO FRIEND (FR_USR_PROFILE_ID_OWNER, FR_USR_PROFILE_ID_RECEIVER) values ('1','2');




CREATE TABLE Transactions (

TRA_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
 
TRA_USR_PROFILE_ID_EMIT INTEGER NOT NULL,

TRA_USR_PROFILE_ID_RECEIV INTEGER NOT NULL,

TRA_DESIGNATION VARCHAR (255) NOT NULL,
 
TRA_DATE DATE NOT NULL,

TRA_AMOUNT DECIMAL (10,3) NOT NULL,

TRA_FEE DECIMAL (10,3) NOT NULL,

FOREIGN KEY (TRA_USR_PROFILE_ID_EMIT) REFERENCES User (USR_ID),

FOREIGN KEY (TRA_USR_PROFILE_ID_RECEIV) REFERENCES User (USR_ID)); 



DROP DATABASE IF EXISTS newpmbtests;

CREATE DATABASE newpmbtests;

USE newpmbtests;



CREATE TABLE Identification (
IDN_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

IDN_EMAIL VARCHAR (100) NOT NULL,

IDN_PASSWORD VARCHAR (100) NOT NULL
);

INSERT INTO Identification  (IDN_EMAIL, IDN_PASSWORD) values('emmanueljurquet@gmail.com', 'nouveaumotdepasse');
INSERT INTO Identification (IDN_EMAIL, IDN_PASSWORD) values ('audrey@gmail.com','motdepasse2');
INSERT INTO Identification (IDN_EMAIL, IDN_PASSWORD) values ('jeannechureau@gmail.com','nouveaumdp3');
INSERT INTO Identification (IDN_EMAIL, IDN_PASSWORD) values ('hanna@gmail.com', 'mdp');




CREATE TABLE User (

USR_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

USR_FK_IDN INTEGER NOT NULL,

USR_F_NAME VARCHAR (100) NOT NULL,

USR_L_NAME VARCHAR (100) NOT NULL,

USR_EMAIL VARCHAR (100) NOT NULL,

USR_BIRTH DATE NOT NULL,

USR_ADDR VARCHAR (100) NOT NULL,

USR_PHONE VARCHAR (100) NOT NULL,

USR_CITY VARCHAR (100) NOT NULL,

USR_ZIP VARCHAR (100) NOT NULL,
 
FOREIGN KEY (USR_FK_IDN) REFERENCES Identification (IDN_ID));

INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('1','Emmanuel',' Jurquet','emmanueljurquet@gmail.com','1979/12/02','10 rue of nowhere',' 07-58-65-98','Paris', '75000');
INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('2','Audrey', 'Guillet','audrey@gmail.com','1984/05/12','10 rue of nowhere', '07-58-55-84','Paris', '75000');
INSERT INTO User (USR_FK_IDN, USR_F_NAME, USR_L_NAME, USR_EMAIL, USR_BIRTH, USR_ADDR, USR_PHONE, USR_CITY, USR_ZIP) VALUES ('3','Jeanne','Chureau','jeannechureau@gmail.com','2013/02/07','10 rue de nulle part', '07-65-85-95', 'Paris','75000');



CREATE TABLE Wallet (

WAL_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
 
WAL_USR_FK_ID INTEGER NOT NULL,

WAL_BALANCE DECIMAL (10,3) NOT NULL,

WAL_VISA VARCHAR (100)  NOT NULL,

WAL_EXPIR VARCHAR (10) NOT NULL, 

WAL_CRYPTO INTEGER (5) NOT NULL,

FOREIGN KEY (WAL_USR_FK_ID) REFERENCES User ( USR_ID));

INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('1', '100.00', '231546598', '10/12', '415');
INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('2', '250.00','213556897', '01/06', '416');
INSERT INTO Wallet (WAL_USR_FK_ID, WAL_BALANCE, WAL_VISA, WAL_EXPIR, WAL_CRYPTO) VALUES ('3', '10.00', '213566456', '05/25', '413');



CREATE TABLE Friend (

FR_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,

FR_USR_PROFILE_ID_OWNER INTEGER NOT NULL,

FR_USR_PROFILE_ID_RECEIVER INTEGER NOT NULL,

FOREIGN KEY (FR_USR_PROFILE_ID_OWNER) REFERENCES User (USR_ID),

FOREIGN KEY (FR_USR_PROFILE_ID_RECEIVER) REFERENCES User (USR_ID)); 

INSERT INTO Friend (FR_USR_PROFILE_ID_OWNER, FR_USR_PROFILE_ID_RECEIVER) values ('1','2');



CREATE TABLE Transactions (

TRA_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
 
TRA_USR_PROFILE_ID_EMIT INTEGER NOT NULL,

TRA_USR_PROFILE_ID_RECEIV INTEGER NOT NULL,

TRA_DESIGNATION VARCHAR (255) NOT NULL,
 
TRA_DATE DATE NOT NULL,

TRA_AMOUNT DECIMAL (10,3) NOT NULL,

TRA_FEE DECIMAL (10,3) NOT NULL,


FOREIGN KEY (TRA_USR_PROFILE_ID_EMIT) REFERENCES User (USR_ID),

FOREIGN KEY (TRA_USR_PROFILE_ID_RECEIV) REFERENCES User (USR_ID)); 





